# config-.yaml
envoy_path_base: "/root"
envoy_path: "/root/envoy"       # Envoy 可执行文件路径
envoy_log: "/root/envoy.log"       # Envoy 日志文件路径
envoy_config: "/root/envoy-mini.yaml"
server_list:                             # Etcd 集群所有节点
  - "149.28.134.50"
server_ip: "149.28.134.50"                    # 当前节点 IP
data_dir: "/root/etcd"                # Etcd 数据目录
#name: "etcd-1"                            # 当前节点名字

scaling:
  username: "root"
  local_path_proxy: "./install/data-proxy"
  remote_path_proxy: "/root/data-proxy"
  binary_proxy: "data-proxy"
  local_path_plane: "./install/data-plane"
  remote_path_plane: "/root/data-plane"
  binary_plane: "data-plane"
  private_key: "/root/.ssh/id_rsa"
  config: "{}"
  ssh_key: "matth:ssh-rsa AAAA= matth@instance-20260202-081539"

node:
  provider: "vultr"        # gcp | aws | azure | vultr | digitalocean | onprem
  continent: "asia"      # ONLY field used for bandwidth / cost query
  country: "japan"          # 可选，用于日志/解释/未来扩展
  city: "tokyo"          # 可选，用于日志/解释/未来扩展
  ip:
    private: "0.0.0.0"  # 内网 IP
    public: "149.28.134.50" # 公网 IP 作为hostname

proxy:
  ips:
    - "149.28.134.50"

# scaling的config代替
#gcp:
#  projectID: "civil-honor-480405-e0"      # 替换为你的 GCP 项目 ID
#  zone: "asia-east2-c"                   # 机房
#  vmPrefix: "scaling-vm-"                     # VM 名称前缀（不是具体名字）
#  credFile: "/root/civil-honor-480405-e0-e62b994bbc27.json"  # GCP 凭证文件路径