# config-.yaml
envoy_path_base: "/root"
envoy_path: "/root/envoy"       # Envoy 可执行文件路径
envoy_log: "/root/envoy.log"       # Envoy 日志文件路径
envoy_config: "/root/envoy-mini.yaml"
server_list:                             # Etcd 集群所有节点
  - "10.170.0.2"
server_ip: "10.170.0.2"                    # 当前节点 IP
data_dir: "/root/etcd"                # Etcd 数据目录
#name: "etcd-1"                            # 当前节点名字

scaling:
  username: "root"
  local_path_proxy: "./install/data-proxy"
  remote_path_proxy: "/root/data-proxy"
  binary_proxy: "data-proxy"
  local_path_plane: "./install/data-plane"
  remote_path_plane: "/root/data-plane"
  binary_plane: "data-plane"
  private_key: "/root/.ssh/id_rsa"

ssh_key: "matth:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyKfXWsf5A1H2Ga0OYZDb2LPhpivEoQatdOBfssmhJxxlNQ4m+TkzVMZGZfFYWUpBigbRKfOtoAGPR0wIc/qEmRpRF6L+9FvBFJZG1t0BnC1uZiydoK8f7taVz9kcHScAjdxXF1malRPGL0su5MLMvwQ5HYyevYpfHlvhTZziVqnTJZR6mnaVYb5vezYZPTgTyKEZABZxpxsc8wUQum7wcr2OffqVJItQa65XJyxHtASNlY8YxQevPuOHUzaX/d6yoCtZMYVTf68JE0etQ+0Fx/HPdlGAlccXiZIyC6vVGQfYylnTo7yl29FpaMhfM/IHc2nPERcPslQKnestE+Z0+IjJXJMtbGYKUrwxhFtYqy22JD2rKLy6r2kR7rKoi3+e9n+GdbH8jranccnrWkj1/rtP7YG8hniXwgoOB86TJp+OoWkiRDtCXE++jxsiegMAcF/gVmChDzH42+5v+vMYI9MI1Prjd4CLqbWDKffuUg94MTJILbKMZIbwqYAkBQtk= matth@instance-20260202-081539"

node:
  provider: "gcp"        # gcp | aws | azure | vultr | digitalocean | onprem
  continent: "Asia"      # ONLY field used for bandwidth / cost query
  country: "Asia"          # 可选，用于日志/解释/未来扩展
  city: "asia-northeast1-b"          # 可选，用于日志/解释/未来扩展

  ip:
    private: "10.170.0.2"  # 内网 IP
    public: "34.96.131.245" # 公网 IP 作为hostname

  # 节点相关配置结束

proxy:
  ips:
    - "34.96.131.245"

gcp:
  projectID: "civil-honor-480405-e0"      # 替换为你的 GCP 项目 ID
  zone: "asia-east2-c"                   # 机房
  vmPrefix: "scaling-vm-"                     # VM 名称前缀（不是具体名字）
  credFile: "/root/civil-honor-480405-e0-e62b994bbc27.json"  # GCP 凭证文件路径